name: Playwright Tests
on:
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies in Playwright
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: Playwright

    - name: Install dependencies in WebAPp
      uses: borales/actions-yarn@v4
      with:
        cmd: install
        dir: WebAPp

    - name: Restore cached node_modules for Playwright
      uses: actions/cache/restore@v4
      with:
        path: Playwright/node_modules
        key: ${{ runner.os }}-Playwright-${{ hashFiles('Playwright/yarn.lock') }}
        fail-on-cache-miss: true

    - name: Restore cached node_modules for WebAPp
      uses: actions/cache/restore@v4
      with:
        path: WebAPp/node_modules
        key: ${{ runner.os }}-WebAPp-${{ hashFiles('WebAPp/yarn.lock') }}
        fail-on-cache-miss: true
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore .NET dependencies
      run: dotnet restore Pdc.sln
      
    - name: Build .NET solution
      run: dotnet build Pdc.sln --configuration Release --no-restore
    
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: Playwright
    
    - name: Run Playwright tests
      run: npx playwright test
      working-directory: Playwright
      env:
        CI: true

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: Playwright/playwright-report/
        retention-days: 7
